name: trivy-security-scanning
on: 
  push: 
  workflow_dispatch:

permissions:
  security-events: write # To upload sarif files

jobs:
  chart-test:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          # output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          image-ref: 'charts/sample-helm-devsecops'
          scan-ref: 'charts/sample-helm-devsecops'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'
